# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink: pretty

# Setup
title:            Yet another blog
tagline:          'A Jekyll theme'
description:      'Just a blog for random stuff in elec-eng, machine learning, DSP and religion i guess'
url:              ""
baseurl:          /

future:           true
author:
  name:           'Edwin Sun'
  url:            https://github.com/Wingmore

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
