# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink: pretty

# Setup
title:            Hire me please
tagline:          'A Jekyll theme'
description:      'Just a blog for some AI, machine learning and religion'
url:              "https://wingmore.github.io"
# url:              "" # For localhost
baseurl:          /

future:           true
author:
  name:           'Edwin Sun'
  url:            https://github.com/Wingmore

paginate:         5
remote_theme:     hyde

# Custom vars
version:          yes

github:
  repo:           https://github.com/Wingmore

collections:
  test:
    output: true
    permalink: /:collection/:path/
    # permalink: pretty

kramdown:
  math_engine: mathjax