# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Blog for me
tagline:          'A Jekyll theme'
description:      'Just a blog for random stuff in elec-eng and religion i guess'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Edwin Sun'
  url:            https://github.com/Wingmore

paginate:         5

# Custom vars
version:          idk

github:
  repo:           https://github.com/Wingmore
