# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink: pretty

# Setup
title:            Blog for me
tagline:          'A Jekyll theme'
description:      'Just a blog for random stuff in elec-eng and religion i guess'
url:              ""
baseurl:          /

future:           true
author:
  name:           'Edwin Sun'
  url:            https://github.com/Wingmore

paginate:         5

# Custom vars
version:          yes

github:
  repo:           https://github.com/Wingmore

collections:
  test:
    output: true
    permalink: /:collection/:path/
    # permalink: pretty
